name = "r3f-metaverse-gallery"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "GALLERY_ARTWORKS"
id = "765a4c8073f7441688bf2e554a43cc3c"
preview_id = "b8b7746369534855a32f936ec75beacc"
